### ISSUE TITLE
DRY: configured_zones, available_zones

### ISSUE THREAD

**Issue by aphor** [saltstack-formulas/bind-formula#114]
Convention over configuration:

If a zone is defined in a pillar, I want the salt states to ensure it is declared in the conf file and also the records are declared in the zone file.

@ppieprzycki thought it was a good idea for Debian in 2947dde649e480091f99552bf7479a0a15c1fb36

It's probably a good idea in general.

**Comment by aanriot** [comment]
Hello @aphor ,

Have you tried to use *available_zones* ? It should declare the zone and manage its content as well.

**Comment by javierbertoli** [comment]
Hi @aphor, AFAICS, it dates way back to ~2015. But there's some documentation on the usage of these 2 variables [here](https://github.com/saltstack-formulas/bind-formula#management-of-zone-files)

TL; RL: you use `configured_zones` to declare which zones are being served by this particular nameserver, being them master, slave, zone files managed or not by this formula or some other way, etc., etc. And then, you use `available_zones` to populate the zone files.

Hope this helps.

**Comment by aphor** [comment]
That helps, but seems over complicated.  

I think the behavior implemented for Debian in 2947dde was a move in the right direction.

Would anyone object to making the formula behave as @aanriot suggested?

**Comment by javierbertoli** [comment]
This issue, #120 and PR #121 are all suggestions that this formula needs some refactoring to DRY/simplify the logic on zone/s - view/s management.

I think that something like (pseudo here, not necessarily correct):

```yaml
views:
  - view1
  - view2
  - viewN

zones:
  zone1:
    enabled: true
    external_file: /path/or/ref/to/source/of/file
    records:
        all the records code
    view:         # If present, zone will be exposed in the corresponding view
       - view1
  zone2:
    enabled: false     # to keep the file, but disable the zone to be served
    external_file: /path/or/ref/to/source/of/file  # if present, file with zone records will be managed externally
  zoneN:

```

Maybe something like this covers all cases we need to consider?

**Comment by aanriot** [comment]
> This issue, #120 and PR #121 are all suggestions that this formula needs some refactoring to DRY/simplify the logic on zone/s - view/s management.

Indeed @javierbertoli , the formula has become too much complicated. Though, I think that we should opt for *bind-ng* states and pillars, like https://github.com/saltstack-formulas/nginx-formula did, to avoid breaking existing setups.

> I think that something like (pseudo here, not necessarily correct):
> 
> ```yaml
> views:
>   - view1
>   - view2
>   - viewN
> 
> zones:
>   zone1:
>     enabled: true
>     external_file: /path/or/ref/to/source/of/file

As the file path is always needed, we may want to use instead:

```
zones:
  zone1:
    enabled: true
    zonefile: /path/or/ref/to/source/of/file
    managed (or external): true
```

>     records:
>         all the records code
>     view:         # If present, zone will be exposed in the corresponding view
>        - view1
>   zone2:
>     enabled: false     # to keep the file, but disable the zone to be served
>     external_file: /path/or/ref/to/source/of/file  # if present, file with zone records will be managed externally
>   zoneN:
> ```
> 
> Maybe something like this covers all cases we need to consider?

It seems to, if we keep a way to detect the file path when it's not defined.
