### ISSUE TITLE
zones -> /srv/salt/zones broken link

### ISSUE THREAD

**Issue by ogabrielsantos** [saltstack-formulas/bind-formula#37]
Why `bind/zones` a symbolic link?
Why it is hardcoded without possibility of custom path?

What about a `root_dir` pointing to `~/workspace/servers/` instead of `/srv/salt`?
What about `file_roots` other than default `base` setup?

````
file_roots:
  dev:
    - /srv/salt/dev/states
    - /srv/salt/prod/states
  prod:
    - /srv/salt/prod/states
````

Currently I need to manual change `bind-formula` in order to make things work.

Maybe add another `file_root` entry pointing to my custom bind directory can work but this seems a hack instead of a default expected approach:

````
file_roots:
  dev:
    - /srv/salt/prod/states/files/var/
    - /srv/salt/dev/states
    - /srv/salt/prod/states
  prod:
    - /srv/salt/prod/states/files/var/
    - /srv/salt/prod/states

var/
└── bind/
    └── hosts
       ├── zone-file1.local
       ├── zone-file2.local
````

EDIT: Hacky symlinks will be a issue [because master stop responding when I've specifics symlinks](https://github.com/saltstack/salt/issues/27856)

tks (:
