### ISSUE TITLE
using HMAC-SHA512 secret breaks bind 

### ISSUE THREAD

**Issue by cybacolt** [saltstack-formulas/bind-formula#40]
```
bind:
  keys:
    "core_dhcp":
    algorithm: HMAC-SHA512
    secret: {{ conf.bind.secret }}
```
creates /etc/bind/named.conf.key:
```
key "core_dhcp" {
  algorithm HMAC-SHA512;
  secret MY-SUP/ER-SECU/RE-K/EY;
};
```
... but bind refuses to restart unless the secret is "quoted". (probably slashes in the key causing issues)

this needs to be fixed in the named.conf.key template:
```
  secret "{{ args['secret'] }}";
```
happy to do a PR for this if its agreeable.
