### ISSUE TITLE
How do to configure slaves?

### ISSUE THREAD

**Issue by bogdanr** [saltstack-formulas/bind-formula#78]
Is there an option to configure slave servers?

**Comment by javierbertoli** [comment]
Hi @bogdanr! Yes. You can add to you pillar something like this

```yaml
bind:
   configured_zones:
    one.slave.zone.com:
      type: slave
    another.slave.zone.org:
      type: slave

  available_zones:
    one.slave.zone.com:
      masters:
        - 1.2.3.4
        - 6.7.8.9
      file: db.one.slave.zone.com.conf

    another.slave.zone.org:
      masters:
        - 1.2.3.3
        - 6.7.8.9
      file: db.another.slave.zone.org.conf
```

That should do it.
